### ISSUE TITLE
Break of min and max functions on Arduino Sam Due

### ISSUE THREAD

**Issue by spangher** [khoih-prog/EthernetWebServer#12]
Hi, I'm trying  to use you library but after adding it to my project I get an error on min and max functions that was previous inside my code.
Before adding your library everything works well.
I've patched platform.txt for SAM Due, as you said. I'm using also EthernetENC.
Is It my fault? I forgot to patch something?
To make my code working again I've to put this definitions after including your library:

#ifndef max
#define max(a,b) (((a) > (b)) ? (a) : (b))
#endif

#ifndef min
#define min(a,b) (((a) < (b)) ? (a) : (b))
#endif

Thanks,
Paolo

**Comment by khoih-prog** [comment]
Thanks for using the library and it's good that you've found out a way to fix the problem. I also think that **it's not your fault at all.** There are too many libraries now, and each one will try to dictate the environment and conflicts will finally arise.

Without the `Minimum Reproducible Code`, it's difficult for anybody to guess what is going on with your code and which library introduces the issue.

It's helpful for other users to **use your solution** if getting the same issue. That's the way you, with your feedback,can contribute back to the Open Source Community.

Regards,
