### ISSUE TITLE
#include <WebServer.h> then compilation error

### ISSUE THREAD

**Issue by qlalfdu** [khoih-prog/EthernetWebServer#15]
Thank you.
Arduino IDE version: 1.8.13
using ESP32

It cannot be used with 'WebServer.h' in the 'SimpleWebSocket' example.
#include <WebServer.h> then compilation error.

**Comment by khoih-prog** [comment]
This [**EthernetWebServer**](https://github.com/khoih-prog/EthernetWebServer) is already a WebServer.
You don't need to add another WebServer by

```
#include <WebServer.h>
```

or duplication linker error will happen.
