### ISSUE TITLE
Problem with your custom ethernet library (W5500-Teensy 4.0)

### ISSUE THREAD

**Issue by adriansmas** [khoih-prog/EthernetWebServer#3]
Hi! I'm working with your library with a teensy 4.0 and Ethernet Chip W5500. With default Ethernet library, I can't send messages longer than 2K. When I paste your custom files of that library I can't send any messages. "HTTP_MAX_CLOSE_WAIT" Timeout.
Do you have any suggestion of what may be my problem?

**Comment by adriansmas** [comment]
Also gif image of "HelloServer2" cannot be sent with the default functions.

**Comment by khoih-prog** [comment]
Did you test with the unmodified Ethernet library? Is it working OK with any simple example, such as HelloServer? 

Just be sure no hardware-related issue.

If OK, test the modified Ethernet library with the simplest example, such as HelloServer.
Can you also post your full code along with any terminal / debug messages?
