### ISSUE TITLE
Use the  EthernetWebserver and  ESP8266Webserver simultaneously

### ISSUE THREAD

**Issue by jepoy11** [khoih-prog/EthernetWebServer#30]
I want to use wifi capability of the esp8266 and connect a Ethernet module(W5500) to have LAN.

I want to connect to different network but serve the same webserver.

So that when I access the ethernet IP and Wifi IP it will show the same webserver.

**Comment by khoih-prog** [comment]
Have a look at [**WiFi and Ethernet Bridge?** #26](https://github.com/khoih-prog/EthernetWebServer/issues/26).

> But to use the high level EthernetWebServer and ESP32 WebServer is currently not ready, unless the library is modified to avoid conflicts.
> I don't think I'll spend time to modify the library as this use case is not popular.
