### ISSUE TITLE
ESP32 with ENC28j60 slow simple HTTP post request 

### ISSUE THREAD

**Issue by sdrshnptl** [khoih-prog/EthernetWebServer#34]
### Slow HTTP POST request on ENC28j60 with ESP32

ESP32 as web client using enc28j60 to post request on local server working very slow around >2200ms.
same request from POSTMAN application takes only 100ms.

### Steps to Reproduce

Using generic simple http post example.

### Expected behavior

Post request supposed to be completed within <200 ms.

### Actual behavior

 \>2200 ms is consumed by httpclient post request.

### Information

Please ensure to specify the following:

* Platform.io version Core 5.1.1·Home 3.3.4
* `ESP32` ESP32 v3.2.0
* Contextual information (e.g. what you were trying to achieve) : fast http post request.
* Anything that might be relevant in your opinion, such as:
  * Operating system windows 10
  * Network configuration wifi

**Comment by khoih-prog** [comment]
Thanks for using the library.

Why you're using bad ENC28J60 while ESP32 has much better WiFi ? There can be some **hard-to-find conflict issue** when you're using both WiFi and **I'm not going to support this strange use case.**

Also please follow the instructions in [**Issue: Bug report**](https://github.com/khoih-prog/EthernetWebServer/issues/new?assignees=&labels=&template=bug_report.md&title=) and post all the information, especially the [**MRE**](https://stackoverflow.com/help/minimal-reproducible-example).

Which ENC28J60 library are you using (UIPEthernet ot EthernetENC)  and which version?

I suggest you try 

1. using the UIPEthernet ot EthernetENC examples first, and report to that library.
2. using plain Arduino IDE, not PIO

I'm not going to spend any time on this,
