### ISSUE TITLE
ARDUINO IDE 1.6.12 compile error with esp8266

### ISSUE THREAD

**Issue by stBasil** [khoih-prog/EthernetWebServer#37]
Arduino IDE version: 1.6.12
ESP32 Core Version 1.0.5
Windows 10

Compile error with esp8266

In file included from D:\Google\DUNYA\WORKS\arduino-1.6.12\libraries\EthernetWebServer\examples\AdvancedWebServer\AdvancedWebServer.ino:44:0:

C:\Users\nrf\AppData\Local\Temp\arduino_build_994772\sketch\defines.h:375:33: fatal error: EthernetLarge.h: No such file or directory#

#include "EthernetLarge.h"

compilation terminated.

**Comment by khoih-prog** [comment]
Please at least read the README's [**Prerequisites**](https://github.com/khoih-prog/EthernetWebServer#prerequisites) and install whatever library you've selected, e.g. [**EthernetLarge**](https://github.com/OPEnSLab-OSU/EthernetLarge). Moreover, please update the Arduino IDE (to current v1.8.16) as well as ESP32 core (to current v2.0.0)

If you don't know how to install the library, please ask in [**Arduino forum**](https://forum.arduino.cc/c/using-arduino/installation-troubleshooting/18).

Good Luck,
