### ISSUE TITLE
Something wrong in http response header

### ISSUE THREAD

**Issue by neardreams** [khoih-prog/EthernetWebServer#41]
Hi 
I'm using this library for my ESP32 and w5100 ethernet board.
Recently I found that there's unexpected chars (0x20, 0x91) in http reponse after "HTTP/1.1" and no http status code which causes http basic auth fail and something strange .
Is there anything I can do or maybe to get an update?
Thanks for help.

@v1.81 + Arduino 1.8.16 + Ethernet.h

**Comment by khoih-prog** [comment]
Close via [PR #42](https://github.com/khoih-prog/EthernetWebServer/pull/42)
