### ISSUE TITLE
Missing ESP definitions .....

### ISSUE THREAD

**Issue by Nourbakhsh-Rad** [khoih-prog/EthernetWebServer#45]
Hi @khoih-prog 
After version 1.8.5, there is no ESP definition in EthernetWebServer.h

`EthernetWebServer.h:105:4: error: #error Not supported board. Please check your Tools->Board setting`

I am using ESP-12E with ENC28J60 Ethernet module and Arduino IDE version 1.8.16 with ESP8266 core 3.0.2

**Comment by khoih-prog** [comment]
Hi @Nourbakhsh-Rad 

Again thanks for spotting my sloppy mistake. I'm definitely needed some coffee then ;-)

I'm confident now to have you testing if there is any more mistake in new [**v1.8.6**](https://github.com/khoih-prog/EthernetWebServer/releases/tag/v1.8.6)

---

### Releases v1.8.6

1. Fix bug not supporting boards. Check [Missing ESP definitions ..... #45](https://github.com/khoih-prog/EthernetWebServer/issues/45)
