### ISSUE TITLE
Needing help !

### ISSUE THREAD

**Issue by kbssa** [khoih-prog/EthernetWebServer#48]
I know that it is not an issue related, but I am geting mad trying to use the EthernetWebServer
 library together with the https://github.com/Aircoookie/Espalexa.

I did some small changes in the Espalexa library and now it compiles wihthout any error, the espalexa server works, but the alexa never discovers the devices.

I am using the W5500, the TCP server and the webserver work very well and fast, but to finish my project I need that the Espalexa library works with this one.

I know that it is compatible with the LAN8720 module, but I can't see why it is not working with the W5500. I don't know the differences between them, as I am not espacialist. I wish I were !

So, if you could help me to find out what I have to change in the Espalexa for it work I will be vary gratefull.

I can pay for your time if you julge necessary.

Sorry If I annoyed you with my problem, it was not my intent.

Thanks in advance.

**Comment by khoih-prog** [comment]
I'm sorry I have no time to help you, especially with the old ESpalexa library.

I suggest that you use my [**SinricPro_Generic** library](https://github.com/khoih-prog/SinricPro_Generic), which supports too many different **boards / Ethernet / WiFi**.

For example **WT32_ETH01** (ESP32 + LAN8720), etc.

Good Luck,
