### ISSUE TITLE
fatal error: functional-vlpp.h: No such file or directory

### ISSUE THREAD

**Issue by kendo55** [khoih-prog/EthernetWebServer#70]
In **Arduino IDE 1.8.19**
with **E. Philhower RP2040 core** (what woorks in other cases very well)
I tried to use  your example  

**AdvancedWebServer_RP2040_SPI1.ino**

with a "**WIZnet 5100S-EVB-Pico**" board, that woorks fine with the lib "https://github.com/WIZnet-ArduinoEthernet/Ethernet"  
I replaced this lib with your lib.

in your original **Exaple AdvancedWebServer_RP2040_SPI1**,
I made the following **mutations**
in the defines.h : 

#define USING_SPI2   false //  true  //muths
IPAddress ip(192, 168, 1, 179);   //muths

At the Verify process the have this error msg:
````
In file included from D:\projekte\RP2040\sketchbook\libraries\EthernetWebServer\src/EthernetWebServer.h:72,
                 from D:\projekte\RP2040\sketchbook\AdvancedWebServer_WIZnetHS1\defines.h:118,
                 from D:\projekte\RP2040\sketchbook\AdvancedWebServer_WIZnetHS1\AdvancedWebServer_WIZnetHS1.ino:44:
D:\projekte\RP2040\sketchbook\libraries\EthernetWebServer\src/EthernetWebServer.hpp:45:10: fatal error: functional-vlpp.h: No such file or directory
   45 | #include <functional-vlpp.h>
      |          ^~~~~~~~~~~~~~~~~~~
compilation terminated.
````

I couldn't find this file anywhere....

Thanks!

**Comment by khoih-prog** [comment]
When using a new library, always check the [**Prerequisites**](https://github.com/khoih-prog/EthernetWebServer#prerequisites) first. Especially when you get a fatal error. Then know that you have to install [**functional-vlpp**](https://github.com/khoih-prog/functional-vlpp) library.
